name: foodify
description: A new Flutter project.
publish_to: "none"
version: 1.0.7+8

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  bottom_bar_page_transition: ^2.0.0
  calendar_appbar: ^0.0.6
  carousel_slider: ^4.0.0
  cloud_firestore: ^3.1.10
  cupertino_icons: ^1.0.2
  dot_navigation_bar: ^1.0.1+4
  eva_icons_flutter: ^3.1.0
  firebase_auth: ^3.3.11
  firebase_core: ^1.13.1
  firebase_storage:
  flutter:
    sdk: flutter
  flutter_typeahead: ^4.0.0
  fraction: ^4.0.1
  get: ^4.3.8
  google_fonts: ^3.0.1
  google_sign_in: ^5.2.4
  hive_flutter: ^1.1.0
  http: ^0.13.4
  iconsax: ^0.0.8
  image_picker: ^0.8.5
  like_button: ^2.0.4
  loadmore: ^2.0.1
  lottie: ^1.2.2
  meilisearch: ^0.5.2
  octo_image: ^1.0.1
  readmore: ^2.1.0
  url_launcher: ^6.0.20
  cached_network_image: ^3.2.0
  morpheus: ^1.2.3
  firebase_dynamic_links: ^4.2.6
  share_plus: ^4.0.7
  path_provider: ^2.0.11
  flutter_dotenv: ^5.0.2

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/
    - images/loaders/
    - images/tags/
    - images/diets/
    - images/courses/
    - images/filter/
    - .env
